- hosts: linodes
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install common packages
      apt:
        name:
          - git
          - net-tools
          - openssh-server
          - python3
          - python3-pip
          - tmux
        state: present

