- name: Add Node.js PPA
  apt_repository:
    repo: deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main
    state: present
    filename: nodesource.list
    key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Install Node.js and npm
  apt:
    name:
      - nodejs
      - npm
    state: present
