- name: Install zsh and p10k
  apt:
    name:
      - zsh
      - git
    state: present

- name: Clone p10k Git repository
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    version: master

- name: Configure zsh theme
  lineinfile:
    path: ~/.zshrc
    line: ZSH_THEME="powerlevel10k/powerlevel10k"
    state: present
